version: '3.7'
services:
  #PHP-FPM service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: 420-php
    restart: unless-stopped
    tty: true
    environment:
      - SERVICE_NAME=app
      - SERVICE_TAGS=dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - 420-network

  #Nginx service
  webserver:
    image: nginx:alpine
    container_name: 420-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    depends_on:
      - app
      - db
    volumes:
      - ./:/var/www
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - 420-network

  # MySQL service
  db:
    image: mysql:latest
    container_name: 420-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "42001:3306"
    environment:
      - MYSQL_DATABASE=420-schema
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=secret
      - SERVICE_NAME=mysql
      - SERVICE_TAGS=dev
    volumes:
      - mysqldata:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - 420-network

#Networks
networks:
  420-network:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local
